export let products = [
  {
    id: 1,
    title: "Silbato Fox 40 Classic",
    price: 20000,
    description: "Uno de los silbatos recomendados por los mejores - 115dB",
    img: "https://res.cloudinary.com/ddtzyipqf/image/upload/v1720048178/classic_f7h8qo.jpg",
    stock: 2,
    category: "accesorios",
  },
  {
    id: 2,
    title: "Silbato Fox 40 Mini",
    price: 22000,
    description: "Version mas pequeña del Fox 40 Classic - 105dB",
    img: "https://res.cloudinary.com/ddtzyipqf/image/upload/v1720048178/mini_ukskkk.jpg",
    stock: 4,
    category: "accesorios",
  },
  {
    id: 3,
    title: "Neceser",
    price: 4000,
    description: "Neceser para guardar todas tus cosas para el partido",
    img: "https://res.cloudinary.com/ddtzyipqf/image/upload/v1720048178/neceser_rbz7cu.jpg",
    stock: 5,
    category: "accesorios",
  },
  {
    id: 4,
    title: "Tarjetas",
    price: 5000,
    description: "Tarjetas hechas con impresora 3D",
    img: "https://res.cloudinary.com/ddtzyipqf/image/upload/v1720048178/tarjetas_blovab.jpg",
    stock: 10,
    category: "accesorios",
  },
  {
    id: 5,
    title: "Campera tiempo libre",
    price: 30000,
    description:
      "Campera en tejido soft (elastizado y sin frisa) de media estación. Con capucha y cordon a ono.",
    img: "https://res.cloudinary.com/ddtzyipqf/image/upload/v1720047090/fshbyacvw8w05k206jqv.jpg",
    stock: 10,
    category: "indumentaria",
  },
  {
    id: 6,
    title: "Pantalon largo",
    price: 20000,
    description: "Pantalon largo para arbitro.",
    img: "https://res.cloudinary.com/ddtzyipqf/image/upload/v1720047090/onwa2czy7krikfg3pmpn.jpg",
    stock: 4,
    category: "indumentaria",
  },
  {
    id: 7,
    title: "Bermuda tiempo libre",
    price: 15000,
    description:
      "Bermuda en dry set antitranspirante. Tejido sintético. No destiñe ni encoje. Escudo bordado.",
    img: "https://res.cloudinary.com/ddtzyipqf/image/upload/v1720047090/q4eohfxoat3huwvi7vzr.jpg",
    stock: 3,
    category: "indumentaria",
  },
];
